version: 2

models:
  - name: stg_users
    description: "ユーザー情報のStagingモデル。rawデータの前処理を行ったもの。"
    columns:
      - name: user_id
        description: "ユーザーID"
        tests:
          - unique
          - not_null
      
      - name: email
        description: "email address"
        tests:
          - unique
          - not_null
